version: '2'

services:
  dev:
    image: data-services-test
    build:
      context: .
      args:
        BUILDER_UID: 1000
    environment:
      DOCKER_TESTING: 'true'
    stdin_open: true
    tty: true
    working_dir: /app
    volumes:
      - './:/app'
      - '$HOME/.cache/pip:/home/builder/.cache/pip'
